# Generated by Django 6.0.2 on 2026-03-02 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_recipe_author_recipe_created_on_recipe_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='ledger.profile'),
            preserve_default=False,
        ),
    ]
